config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  resources :entries

  # Defines the root path route ("/")
  root "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  before_validation :set_body_html

  validates :body_markdown, presence: true
  validates :body_html, presence: true

  scope :published, -> () {
    where(draft: false).and(
      where("published_at < ?", Time.current)
    )
  }

  private

  def set_body_html
    self.body_html = body_markdown
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  def index
    # TODO: show all for authenticated users.
    @entries = Entry.published.order(published_at: :desc)
  end

  def show
  end

  def new
    @entry = Entry.new
  end

  def edit
  end

  def create
    @entry = Entry.new(entry_params)

    if @entry.save
      redirect_to @entry, notice: "Entry was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: "Entry was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @entry.destroy!
    redirect_to entries_path, notice: "Entry was successfully destroyed.", status: :see_other
  end

  private
    def set_entry
      @entry = Entry.published.find(params.expect(:id))
    end

    def entry_params
      params.expect(entry: [ :title, :draft, :published_at, :body_markdown, :body_html ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>" class="entry">
  <h2><%= link_to_unless_current entry.title, entry_path(entry) %></h2>
  <div class="meta"><%= l entry.published_at, format: :long %></div>
  <%= sanitize entry.body_html %>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :draft, style: "display: block" %>
    <%= form.checkbox :draft %>
  </div>

  <div>
    <%= form.label :published_at, style: "display: block" %>
    <%= form.datetime_field :published_at %>
  </div>

  <div>
    <%= form.label :body_markdown, style: "display: block" %>
    <%= form.textarea :body_markdown %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<% content_for :title, "Editing entry" %>

<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

app/views/entries/index.html.erb
<div id="entries">
  <% @entries.each do |entry| %>
    <%= render entry %>
  <% end %>
</div>

app/views/entries/new.html.erb
<% content_for :title, "New entry" %>

<h1>New entry</h1>

<%= render "form", entry: @entry %>

app/views/entries/show.html.erb
<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Develumpen" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <header>
        <%= link_to_unless_current "develumpen.com", root_path %>
      </header>
      <p style="color: green"><%= notice %></p>
      <%= yield %>
    </div>
  </body>
</html>